CREATE TABLE ERROR (
ID  uuid DEFAULT uuid_generate_v4(),
DESCRIPTION VARCHAR(50) NOT NULL,
ENVIRONMENT VARCHAR(50) NOT NULL,
LOG VARCHAR(255) NOT NULL,
LEVEL CHAR(1) NOT NULL,
ORIGIN VARCHAR(50) NOT NULL,
FREQUENCY INT NOT NULL,
EVENT_DATE timestamp without time zone NOT NULL
);