CREATE TABLE EVENTOS (
ID  uuid DEFAULT uuid_generate_v4(),
DESCRICAO VARCHAR(50) NOT NULL,
LOG VARCHAR(255) NOT NULL,
LEVEL CHAR(1) NOT NULL,
ORIGEM VARCHAR(50) NOT NULL,
QUANTIDADE INT NOT NULL,
DATA_EVENTO timestamp without time zone NOT NULL
)